config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#top'
  resources :books
  resources :users
  resources :home, only: [:about] do
  	collection do
  		get 'about'
  	end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  attachment :profile_image
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		user_path(current_user.id)
	end
	def after_sign_out_path_for(resource)
		root_path
	end
	private
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
		devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]
	def index
		@books = Book.all
		@book = Book.new
		@user = current_user
	end
	def show
		@book = Book.find(params[:id])
		@user = User.find(@book.user.id)
	end
	def create
		@book = Book.new(book_params)
		@books = Book.all
		@book.user_id = current_user.id
		@user = current_user
		if @book.save
			flash[:notice] = "Book was successfully created."
			redirect_to book_path(@book)
		else
			render "index"
		end
	end
	def edit
		@book = Book.find(params[:id])
	end
	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "Book was successfully updated."
			redirect_to book_path(@book)
		else
			render "edit"
		end
	end
	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to books_path
	end
	private
	def book_params
		params.require(:book).permit(:title, :body)
	end
	def correct_user
		@book = Book.find(params[:id])
    	user = User.find(@book.user.id)
    	if current_user != user
    	redirect_to books_path
    	end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def about
		render "home/home"
	end
	def top
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  #before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  #def configure_sign_up_params
    #devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  #end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]
	def index
		@users = User.all
		@book = Book.new
		@user = current_user
	end
	def show
		@book = Book.new
		@user = User.find(params[:id])
		@books = @user.books
	end
	def edit
		@user = User.find(params[:id])
	end
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:notice] = "User was successfully updated."
			redirect_to user_path(@user)
		else
			render "edit"
		end
	end
	private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end
	def correct_user
    	user = User.find(params[:id])
    	if current_user != user
    	redirect_to user_path(current_user)
    	end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_error_messages.html.erb
<% if @book.errors.any? %>
	<div class="alert alert-warning">
		<ul>
			<% @book.errors.full_messages.each do |message| %>
				<li><%= message + ' error' %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/books/_list.html.erb
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "100x100" %>
		<table class="table">
			<tbody>
				<tr>
					<th>name</th>
					<th><%= user.name %></th>
				</tr>
				<tr>
					<th>introduction</th>
					<th><%= user.introduction %></th>
				</tr>
			</tbody>
		</table>
		<div class="row">
			<% if user == current_user %>
				<%= link_to "", edit_user_path(user.id), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
			<% else %>
				<%= link_to "", user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
			<% end %>
		</div>
		<h2>New book</h2>
		<%= render 'books/error_messages'%>
		<%= form_for(book) do |f| %>
			<div class="field row">
				<label>Title</label>
				<%= f.text_field :title, class: "col-xs-12 book_title" %>
			</div>
			<div class="field row">
				<label>Body</label>
				<%= f.text_area :body, class: "col-xs-12 book_body" %>
			</div>
			<div class="actions row">
				<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
			</div>
		<% end %>
	</div>

app/views/books/edit.html.erb
<div class="col-md-6 col-md-offset-3">
	<h1>Editing Book</h1>
	<%= render 'books/error_messages'%>
	<%= form_for(@book) do |f| %>
		<div class="field row">
			<label>Title</label>
			<%= f.text_field :title, class: "col-xs-12 book_title" %>
		</div>
		<div class="field row">
			<label>Body</label>
			<%= f.text_area :body, class: "col-xs-12 book_body" %>
		</div>
		<div class="action row">
			<%= f.submit "Update Book", class: "btn btn-primary col-xs-12" %>
		</div>
	<% end %>
	<%= link_to "Show", book_path(@book.id) %>
	|
	<%= link_to "Back", books_path %>
</div>

app/views/books/index.html.erb

<div class="row">
	<%= render 'books/list', user: @user, book: @book %>
	<div class="col-xs-9">
		<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan=3></th>
				</tr>
			</thead>
			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to (book.user) do %>
								<%= attachment_image_tag book.user, :profile_image, size: "40x40" , fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td>
							<%= link_to book_path(book.id) do %>
								<%= book.title %>
							<% end %>
						</td>
						<td><%= book.body %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
    </div>
<% end %>
<div class="row">
	<%= render 'books/list', user: @user, book: @book %>
	<div class="col-xs-9">
		<h2>Book detail</h2>
		<table class="table table-hover table-inverse">
			<tbody>
					<tr>
						<% if @user == current_user %>
							<td>
								<%= link_to user_path(@book.user) do %>
									<%= attachment_image_tag @book.user, :profile_image, size: "40x40" , fallback: "no_image.jpg" %>
									<br>
									<%= @user.name %>
								<% end %>
							</td>
							<td>
								<%= link_to book_path(@book.id) do %>
									<%= @book.title %>
								<% end %>
							</td>
							<td><%= @book.body %></td>
							<td>
								<%= link_to "Edit", edit_book_path(@book.id), class: "btn-sm btn-success" %>
							</td>
							<td>
								<%= link_to "Destroy", book_path(@book.id), class: "btn-sm btn-danger", method: :delete, "data-confirm" => "本当に消しますか?" %>
							</td>
						<% else %>
							<td>
								<%= link_to user_path(@book.user) do %>
									<%= attachment_image_tag @book.user, :profile_image, size: "40x40" , fallback: "no_image.jpg", class: "img-responsive pull-left profile-thumb" %>
									<br>
									<%= @user.name %>
								<% end %>
							</td>
							<td>
								<%= link_to book_path(@book.id) do %>
									<%= @book.title %>
								<% end %>
							</td>
							<td><%= @book.body %></td>
						<% end %>
					</tr>
			</tbody>
		</table>
	</div>
</div>

app/views/home/home.html.erb
<p id="notice"></p>
<h1>Welcome to 
	<span class="glyphicon glyphicon-book"></span>
	<strong>Bookers</strong>
	!
</h1>

app/views/home/top.html.erb
<% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
    </div>
<% end %>
<div class="row">
	<div class="top-message col-md-offset-3 col-md-6">
		<h1>welcome to
			<span class="glyphicon glyphicon-book">
				<strong>Bookers</strong>
				!!
			</span>
		</h1>
		<p>In
			<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>
			,
		</p>
		<p>you can share and exchange your opinions , inpressions , and emotions</p>
		<p> about various books!</p>
		<div class="btn-wrapper">
			<div class="row">
				<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>
			</div>
			<div class="row">
				<%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Booker2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="container">
          <nav class="nav navbar-nar navber-left float-left">
            <span>Bookers</span>
          </nav>
          <nav>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li>
                  <%= link_to ' Home', user_path(current_user), {class: "glyphicon glyphicon-home"} %>
                </li>
                <li>
                  <%= link_to ' Users', users_path, {class: "glyphicon glyphicon-user"} %>
                </li>
                <li>
                  <%= link_to ' Books', books_path, {class: "glyphicon glyphicon-book"} %>
                </li>
                <li>
                  <%= link_to ' logout', destroy_user_session_path, {method: "delete", class: "glyphicon glyphicon-log-in"} %>
                </li>
              <% else %>

                <li>
                  <%= link_to ' Home', root_path, {class: "glyphicon glyphicon-home"} %>
                </li>
                <li>
                  <%= link_to ' About', about_home_index_path, {class: "glyphicon glyphicon-link"} %>
                </li>
                <li>
                  <%= link_to ' sign up', new_user_registration_path, {class: "glyphicon glyphicon-edit"} %>
                </li>
                <li>
                  <%= link_to ' login', new_user_session_path, {class: "glyphicon glyphicon-log-in"} %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
    </header><!-- /header -->
    <div class="body">
      <div class="container">
        <p id="notice"></p>
        <%= yield %>
      </div>
    </div>
    <footer>
        <div class="container">
          <div class="row">
            <div class="col-xs-3 col-xs-offset-9">
              <p>CopyRight Infratop.inc</p>
            </div>
          </div>
        </div>
    </footer>
  </body>
</html>

app/views/users/_error_messages_user.html.erb
<% if @user.errors.any? %>
	<div class="alert alert-warning">
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message + ' error' %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= render 'users/error_messages_user'%>
<%= form_for(@user) do |f| %>
	<div class="field">
		<label>Name</label>
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<label>Image</label>
		<%= f.attachment_field :profile_image %>
	</div>
	<div class="field">
		<label>Introduction</label>
		<%= f.text_area :introduction %>
	</div>
	<div class="action">
		<%= f.submit "Update User" %>
	</div>
<% end %>

app/views/users/index.html.erb
<div class="row">
	<%= render 'books/list', user: @user, book: @book %>
	<div class="col-xs-9">
		<h2>Users</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan=3></th>
				</tr>
			</thead>
			<tbody>
				<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag user, :profile_image, size: "40x40" , fallback: "no_image.jpg" %></td>
						<td><%= user.name %></td>
						<td><%= link_to 'Show', user_path(user.id) %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
    <div class="flash">
        <%= flash[:notice] %>
    </div>
<% end %>
<div class="row">
	<%= render 'books/list', user: @user, book: @book %>
	<div class="col-xs-9">
		<h2>Books</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Body</th>
					<th colspan="3" ></th>
				</tr>
			</thead>
			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(@user.id) do %>
								<%= attachment_image_tag book.user, :profile_image, size: "40x40" , fallback: "no_image.jpg" %>
							<% end %>
						</td>
						<td><%= link_to book_path(book.id) do %>
								<%= book.title %>
							<% end %>
						</td>
						<td><%= book.body %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>